#!/bin/bash

# Define the directory
WALLPAPER_DIR="$HOME/.config/wallpapers"

# Check if the directory exists
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: Directory $WALLPAPER_DIR does not exist."
    exit 1
fi

# Find files in the directory
FILES=("$WALLPAPER_DIR"/*)

# Check if there are any files in the directory
if [ ${#FILES[@]} -eq 0 ]; then
    echo "No files found in the directory."
    exit 1
fi

# Select a random file and store the path in a variable
RANDOM_FILE=${FILES[RANDOM % ${#FILES[@]}]}

# Output the random file path
echo "Randomly selected file path: $RANDOM_FILE"

wal -i $RANDOM_FILE
$HOME/.confg/waybar/launch-waybar
swww img $RANDOM_FILE --transition-step 10
